version: '3'
services:
  connector-greynoise:
    image: opencti/connector-greynoise:6.6.6
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=GreyNoise
      - CONNECTOR_SCOPE=IPv4-Addr
      - CONNECTOR_AUTO=true
      - CONNECTOR_LOG_LEVEL=error
      - GREYNOISE_KEY=ChangeMe
      - GREYNOISE_MAX_TLP=TLP:AMBER
      - "GREYNOISE_NAME=GreyNoise Internet Scanner"
      - "GREYNOISE_DESCRIPTION=GreyNoise collects and analyzes untargeted, widespread, and opportunistic scan and attack activity that reaches every server directly connected to the Internet."
      - GREYNOISE_SIGHTING_NOT_SEEN=false
      - GREYNOISE_INDICATOR_SCORE_MALICIOUS=90
      - GREYNOISE_INDICATOR_SCORE_SUSPICIOUS=70
      - GREYNOISE_INDICATOR_SCORE_BENIGN=20
    restart: always
